<a href="https://colab.research.google.com/github/alberzenon/Python_basic/blob/master/Libreri__numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

A lo largo de las próximas secciones introduciremos el array multidimensional ndarray, estructura básica ofrecida por la librería NumPy, así como las funciones y herramientas creadas entorno a éste.

La librería NumPy es una librería fundamental en el análisis de datos y es la base sobre la que se fundamentan otras muchas -incluyendo la mayoría de las librerías de alto nivel usadas en Data Science-. Ofrece la estructura multidimensional ndarray (llamada frecuentemente array, simplemente), herramientas para su gestión, funciones matemáticas de diversa naturaleza en torno al array, funciones de alto nivel de álgebra lineal y herramientas para la generación de números pseudo-aleatorios.

Su primera versión (en 1995) se llamó Numeric, y no fue hasta 2006 cuando recibió el nombre con el que la conocemos ahora (NumPy, de "Numeric Python")

La documentación oficial está disponible en el sitio web de NumPy.

In [1]:
#Esta librería se importa habitualmente con el alias np:


import numpy as np
print(np.__version__)



1.19.5


In [2]:
#NumPy da solución, entre otras cosas, a la necesidad de operar con colecciones de valores de una forma eficiente. Así, por ejemplo, si partimos de las siguientes listas:


m = [1, 2, 3]

n = [3, 4, 5]



In [3]:
m+n

[1, 2, 3, 3, 4, 5]

NumPy ofrece una alternativa a las listas de datos de Python: el array multidimensional (o simplemente array). Éste es semejante a la lista de Python pero permite realizar operaciones entre ellos, u operaciones entre escalares y ellos, o ejecutar ciertas operaciones sobre todos los elementos del array de forma simultánea.

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
#hemos creado un array unidimensional conteniendo los valores 1, 2, 3. Podemos aplicarle una función que eleva cada valor del array al cuadrado:
np.square(a)

array([1, 4, 9])

In [7]:
#O, si tenemos otro array o un escalar, podemos realizar operaciones entre ellos:


b = np.array([5, 6, 7])


In [8]:
a + b

array([ 6,  8, 10])

In [9]:
a - 2

array([-1,  0,  1])

Los arrays son contenedores multidimensionales para datos homogéneos. Es decir, todos los datos contenidos en un array deberán ser del mismo tipo. Todos los arrays tiene un número de dimensiones (ndim), un tamaño (shape) que define el número de elementos en cada dimensión del array, y un tipo (dtype) que describe el tipo de los datos contenidos en el array.


La función array
**texto en negrita**
La función numpy.array
es la forma más simple de crear un array a partir de un iterador como una simple lista (el iterador también puede ser otro array NumPy). En este ejemplo, partimos de una lista n y creamos un array, mostrando el número de dimensiones (atributo ndim), su tamaño (accesible a través de su atributo shape) y el tipo de los datos que contiene (accesible a través de su atributo dtype):

In [10]:
n=[1, 2, 3]
m=np.array(n)

In [11]:
m.dtype

dtype('int64')

In [12]:
m.ndim

1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')